micronaut:
  application:
    name: store
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  server:
    port: 8082
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/store
    driverClassName: org.postgresql.Driver
    username: usr02
    password: XrRVlUr6SCIHVo
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        
#tracing:
#  jaeger:
#    enabled: true
#    sampler:
#      probability: 0.5
#    sender:
##      agent-host: localhost
##      agent-port: 5775
#    reporter:
#      log-spans: true
#    expand-exception-logs: true