micronaut:
  application:
    name: client
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  server:
    port: 8081
  http:
    client:
      log-level: info
datasources:
  default:
    url: jdbc:postgresql://localhost:5431/client
    driverClassName: org.postgresql.Driver
    username: usr01
    password: 5Z8Qn3NSdTT1xa
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false